const elements = [
  {
    name: "Hydrogen",
    appearance: "colorless gas",
    category: "diatomic nonmetal",
    discovered_by: "Henry Cavendish",
    number: 1,
    period: 1,
    group: 1,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Hydrogen",
    summary:
      "Hydrogen is a chemical element with chemical symbol H and atomic number 1. With an atomic weight of 1.00794 u, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.",
    symbol: "H",
    position: { row: 1, col: 1 },
    block: "s",
  },
  {
    name: "Helium",
    appearance:
      "colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field",
    category: "noble gas",
    discovered_by: "Pierre Janssen",
    number: 2,
    period: 1,
    group: 18,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Helium",
    summary:
      "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table. Its boiling and melting points are the lowest among all the elements.",
    symbol: "He",
    position: { row: 1, col: 18 },
    block: "s",
  },
  {
    name: "Lithium",
    appearance: "silvery-white",
    category: "alkali metal",
    discovered_by: "Johan August Arfwedson",
    number: 3,
    period: 2,
    group: 1,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Lithium",
    summary:
      'Lithium (from Greek:λίθος lithos, "stone") is a chemical element with the symbol Li and atomic number 3. It is a soft, silver-white metal belonging to the alkali metal group of chemical elements. Under standard conditions it is the lightest metal and the least dense solid element.',
    symbol: "Li",
    position: { row: 2, col: 1 },
    block: "s",
  },
  {
    name: "Beryllium",
    appearance: "white-gray metallic",
    category: "alkaline earth metal",
    discovered_by: "Louis Nicolas Vauquelin",
    number: 4,
    period: 2,
    group: 2,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Beryllium",
    summary:
      "Beryllium is a chemical element with symbol Be and atomic number 4. It is created through stellar nucleosynthesis and is a relatively rare element in the universe. It is a divalent element which occurs naturally only in combination with other elements in minerals.",
    symbol: "Be",
    position: { row: 2, col: 2 },
    block: "s",
  },
  {
    name: "Boron",
    appearance: "black-brown",
    category: "metalloid",
    discovered_by: "Joseph Louis Gay-Lussac",
    number: 5,
    period: 2,
    group: 13,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Boron",
    summary:
      "Boron is a metalloid chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in both the Solar system and the Earth's crust. Boron is concentrated on Earth by the water-solubility of its more common naturally occurring compounds, the borate minerals.",
    symbol: "B",
    position: { row: 2, col: 13 },
    block: "p",
  },
  {
    name: "Carbon",
    appearance: null,
    category: "polyatomic nonmetal",
    discovered_by: "Ancient Egypt",
    number: 6,
    period: 2,
    group: 14,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Carbon",
    summary:
      'Carbon (from Latin:carbo "coal") is a chemical element with symbol C and atomic number 6. On the periodic table, it is the first (row 2) of six elements in column (group) 14, which have in common the composition of their outer electron shell. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.',
    symbol: "C",
    position: { row: 2, col: 14 },
    block: "p",
  },
  {
    name: "Nitrogen",
    appearance: "colorless gas, liquid or solid",
    category: "diatomic nonmetal",
    discovered_by: "Daniel Rutherford",
    number: 7,
    period: 2,
    group: 15,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Nitrogen",
    summary:
      "Nitrogen is a chemical element with symbol N and atomic number 7. It is the lightest pnictogen and at room temperature, it is a transparent, odorless diatomic gas. Nitrogen is a common element in the universe, estimated at about seventh in total abundance in the Milky Way and the Solar System.",
    symbol: "N",
    position: { row: 2, col: 15 },
    block: "p",
  },
  {
    name: "Oxygen",
    appearance: null,
    category: "diatomic nonmetal",
    discovered_by: "Carl Wilhelm Scheele",
    number: 8,
    period: 2,
    group: 16,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Oxygen",
    summary:
      "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table and is a highly reactive nonmetal and oxidizing agent that readily forms compounds (notably oxides) with most elements. By mass, oxygen is the third-most abundant element in the universe, after hydrogen and helium.",
    symbol: "O",
    position: { row: 2, col: 16 },
    block: "p",
  },
  {
    name: "Fluorine",
    appearance: null,
    category: "diatomic nonmetal",
    discovered_by: "André-Marie Ampère",
    number: 9,
    period: 2,
    group: 17,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Fluorine",
    summary:
      "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions. As the most electronegative element, it is extremely reactive:almost all other elements, including some noble gases, form compounds with fluorine.",
    symbol: "F",
    position: { row: 2, col: 17 },
    block: "p",
  },
  {
    name: "Neon",
    appearance:
      "colorless gas exhibiting an orange-red glow when placed in a high-voltage electric field",
    category: "noble gas",
    discovered_by: "Morris Travers",
    number: 10,
    period: 2,
    group: 18,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Neon",
    summary:
      "Neon is a chemical element with symbol Ne and atomic number 10. It is in group 18 (noble gases) of the periodic table. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.",
    symbol: "Ne",
    position: { row: 2, col: 18 },
    block: "p",
  },
  {
    name: "Sodium",
    appearance: "silvery white metallic",
    category: "alkali metal",
    discovered_by: "Humphry Davy",
    number: 11,
    period: 3,
    group: 1,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Sodium",
    summary:
      "Sodium is a chemical element with symbol Na (from Latin natrium) and atomic number 11. It is a soft, silver-white, highly reactive metal. In the Periodic table it is in column 1 (alkali metals), and shares with the other six elements in that column that it has a single electron in its outer shell, which it readily donates, creating a positively charged atom—a cation.",
    symbol: "Na",
    position: { row: 3, col: 1 },
    block: "s",
  },
  {
    name: "Magnesium",
    appearance: "shiny grey solid",
    category: "alkaline earth metal",
    discovered_by: "Joseph Black",
    number: 12,
    period: 3,
    group: 2,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Magnesium",
    summary:
      "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (group 2, or alkaline earth metals) of the periodic table:all group 2 elements have the same electron configuration in the outer electron shell and a similar crystal structure.",
    symbol: "Mg",
    position: { row: 3, col: 2 },
    block: "s",
  },
  {
    name: "Aluminium",
    appearance: "silvery gray metallic",
    category: "post-transition metal",
    discovered_by: "Hans Christian Ørsted",
    number: 13,
    period: 3,
    group: 13,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Aluminium",
    summary:
      "Aluminium (or aluminum; see different endings) is a chemical element in the boron group with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal. Aluminium is the third most abundant element (after oxygen and silicon), and the most abundant metal, in the Earth's crust.",
    symbol: "Al",
    position: { row: 3, col: 13 },
    block: "p",
  },
  {
    name: "Silicon",
    appearance: "crystalline, reflective with bluish-tinged faces",
    category: "metalloid",
    discovered_by: "Jöns Jacob Berzelius",
    number: 14,
    period: 3,
    group: 14,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Silicon",
    summary:
      "Silicon is a chemical element with symbol Si and atomic number 14. It is a tetravalent metalloid, more reactive than germanium, the metalloid directly below it in the table. Controversy about silicon's character dates to its discovery.",
    symbol: "Si",
    position: { row: 3, col: 14 },
    block: "p",
  },
  {
    name: "Phosphorus",
    appearance: "colourless, waxy white, yellow, scarlet, red, violet, black",
    category: "polyatomic nonmetal",
    discovered_by: "Hennig Brand",
    number: 15,
    period: 3,
    group: 15,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Phosphorus",
    summary:
      "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms—white phosphorus and red phosphorus—but because it is highly reactive, phosphorus is never found as a free element on Earth. Instead phosphorus-containing minerals are almost always present in their maximally oxidised state, as inorganic phosphate rocks.",
    symbol: "P",
    position: { row: 3, col: 15 },
    block: "p",
  },
  {
    name: "Sulfur",
    appearance: "lemon yellow sintered microcrystals",
    category: "polyatomic nonmetal",
    discovered_by: "Ancient china",
    number: 16,
    period: 3,
    group: 16,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Sulfur",
    summary:
      "Sulfur or sulphur (see spelling differences) is a chemical element with symbol S and atomic number 16. It is an abundant, multivalent non-metal. Under normal conditions, sulfur atoms form cyclic octatomic molecules with chemical formula S8.",
    symbol: "S",
    position: { row: 3, col: 16 },
    block: "p",
  },
  {
    name: "Chlorine",
    appearance: "pale yellow-green gas",
    category: "diatomic nonmetal",
    discovered_by: "Carl Wilhelm Scheele",
    number: 17,
    period: 3,
    group: 17,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Chlorine",
    summary:
      "Chlorine is a chemical element with symbol Cl and atomic number 17. It also has a relative atomic mass of 35.5. Chlorine is in the halogen group (17) and is the second lightest halogen following fluorine.",
    symbol: "Cl",
    position: { row: 3, col: 17 },
    block: "p",
  },
  {
    name: "Argon",
    appearance:
      "colorless gas exhibiting a lilac/violet glow when placed in a high-voltage electric field",
    category: "noble gas",
    discovered_by: "Lord Rayleigh",
    number: 18,
    period: 3,
    group: 18,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Argon",
    summary:
      "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third most common gas in the Earth's atmosphere, at 0.934% (9,340 ppmv), making it over twice as abundant as the next most common atmospheric gas, water vapor (which averages about 4000 ppmv, but varies greatly), and 23 times as abundant as the next most common noble gas, neon (18 ppmv).",
    symbol: "Ar",
    position: { row: 3, col: 18 },
    block: "p",
  },
  {
    name: "Potassium",
    appearance: "silvery gray",
    category: "alkali metal",
    discovered_by: "Humphry Davy",
    number: 19,
    period: 4,
    group: 1,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Potassium",
    summary:
      "Potassium is a chemical element with symbol K (from Neo-Latin kalium) and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name derives. In the periodic table, potassium is one of the alkali metals.",
    symbol: "K",
    position: { row: 4, col: 1 },
    block: "s",
  },
  {
    name: "Calcium",
    appearance: "dull gray, silver; with a pale yellow tint",
    category: "alkaline earth metal",
    discovered_by: "Humphry Davy",
    number: 20,
    period: 4,
    group: 2,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Calcium",
    summary:
      "Calcium is a chemical element with symbol Ca and atomic number 20. Calcium is a soft gray alkaline earth metal, fifth-most-abundant element by mass in the Earth's crust. The ion Ca2+ is also the fifth-most-abundant dissolved ion in seawater by both molarity and mass, after sodium, chloride, magnesium, and sulfate.",
    symbol: "Ca",
    position: { row: 4, col: 2 },
    block: "s",
  },
  {
    name: "Scandium",
    appearance: "silvery white",
    category: "transition metal",
    discovered_by: "Lars Fredrik Nilson",
    number: 21,
    period: 4,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Scandium",
    summary:
      "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been sometimes classified as a rare earth element, together with yttrium and the lanthanoids. It was discovered in 1879 by spectral analysis of the minerals euxenite and gadolinite from Scandinavia.",
    symbol: "Sc",
    position: { row: 4, col: 3 },
    block: "d",
  },
  {
    name: "Titanium",
    appearance: "silvery grey-white metallic",
    category: "transition metal",
    discovered_by: "William Gregor",
    number: 22,
    period: 4,
    group: 4,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Titanium",
    summary:
      "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density and high strength. It is highly resistant to corrosion in sea water, aqua regia and chlorine.",
    symbol: "Ti",
    position: { row: 4, col: 4 },
    block: "d",
  },
  {
    name: "Vanadium",
    appearance: "blue-silver-grey metal",
    category: "transition metal",
    discovered_by: "Andrés Manuel del Río",
    number: 23,
    period: 4,
    group: 5,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Vanadium",
    summary:
      "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery grey, ductile and malleable transition metal. The element is found only in chemically combined form in nature, but once isolated artificially, the formation of an oxide layer stabilizes the free metal somewhat against further oxidation.",
    symbol: "V",
    position: { row: 4, col: 5 },
    block: "d",
  },
  {
    name: "Chromium",
    appearance: "silvery metallic",
    category: "transition metal",
    discovered_by: "Louis Nicolas Vauquelin",
    number: 24,
    period: 4,
    group: 6,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Chromium",
    summary:
      "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in Group 6. It is a steely-gray, lustrous, hard and brittle metal which takes a high polish, resists tarnishing, and has a high melting point.",
    symbol: "Cr",
    position: { row: 4, col: 6 },
    block: "d",
  },
  {
    name: "Manganese",
    appearance: "silvery metallic",
    category: "transition metal",
    discovered_by: "Torbern Olof Bergman",
    number: 25,
    period: 4,
    group: 7,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Manganese",
    summary:
      "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in minerals in combination with iron. Manganese is a metal with important industrial metal alloy uses, particularly in stainless steels.",
    symbol: "Mn",
    position: { row: 4, col: 7 },
    block: "d",
  },
  {
    name: "Iron",
    appearance: "lustrous metallic with a grayish tinge",
    category: "transition metal",
    discovered_by: "5000 BC",
    number: 26,
    period: 4,
    group: 8,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Iron",
    summary:
      "Iron is a chemical element with symbol Fe (from Latin:ferrum) and atomic number 26. It is a metal in the first transition series. It is by mass the most common element on Earth, forming much of Earth's outer and inner core.",
    symbol: "Fe",
    position: { row: 4, col: 8 },
    block: "d",
  },
  {
    name: "Cobalt",
    appearance: "hard lustrous gray metal",
    category: "transition metal",
    discovered_by: "Georg Brandt",
    number: 27,
    period: 4,
    group: 9,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Cobalt",
    summary:
      "Cobalt is a chemical element with symbol Co and atomic number 27. Like nickel, cobalt in the Earth's crust is found only in chemically combined form, save for small deposits found in alloys of natural meteoric iron. The free element, produced by reductive smelting, is a hard, lustrous, silver-gray metal.",
    symbol: "Co",
    position: { row: 4, col: 9 },
    block: "d",
  },
  {
    name: "Nickel",
    appearance: "lustrous, metallic, and silver with a gold tinge",
    category: "transition metal",
    discovered_by: "Axel Fredrik Cronstedt",
    number: 28,
    period: 4,
    group: 10,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Nickel",
    summary:
      "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge. Nickel belongs to the transition metals and is hard and ductile.",
    symbol: "Ni",
    position: { row: 4, col: 10 },
    block: "d",
  },
  {
    name: "Copper",
    appearance: "red-orange metallic luster",
    category: "transition metal",
    discovered_by: "Middle East",
    number: 29,
    period: 4,
    group: 11,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Copper",
    summary:
      "Copper is a chemical element with symbol Cu (from Latin:cuprum) and atomic number 29. It is a soft, malleable and ductile metal with very high thermal and electrical conductivity. A freshly exposed surface of pure copper has a reddish-orange color.",
    symbol: "Cu",
    position: { row: 4, col: 11 },
    block: "d",
  },
  {
    name: "Zinc",
    appearance: "silver-gray",
    category: "transition metal",
    discovered_by: "India",
    number: 30,
    period: 4,
    group: 12,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Zinc",
    summary:
      "Zinc, in commerce also spelter, is a chemical element with symbol Zn and atomic number 30. It is the first element of group 12 of the periodic table. In some respects zinc is chemically similar to magnesium:its ion is of similar size and its only common oxidation state is +2.",
    symbol: "Zn",
    position: { row: 4, col: 12 },
    block: "d",
  },
  {
    name: "Gallium",
    appearance: "silver-white",
    category: "post-transition metal",
    discovered_by: "Lecoq de Boisbaudran",
    number: 31,
    period: 4,
    group: 13,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Gallium",
    summary:
      "Gallium is a chemical element with symbol Ga and atomic number 31. It is in group 13 of the periodic table, and thus has similarities to the other metals of the group, aluminium, indium, and thallium. Gallium does not occur as a free element in nature, but as gallium(III) compounds in trace amounts in zinc ores and in bauxite.",
    symbol: "Ga",
    position: { row: 4, col: 13 },
    block: "p",
  },
  {
    name: "Germanium",
    appearance: "grayish-white",
    category: "metalloid",
    discovered_by: "Clemens Winkler",
    number: 32,
    period: 4,
    group: 14,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Germanium",
    summary:
      "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard, grayish-white metalloid in the carbon group, chemically similar to its group neighbors tin and silicon. Purified germanium is a semiconductor, with an appearance most similar to elemental silicon.",
    symbol: "Ge",
    position: { row: 4, col: 14 },
    block: "p",
  },
  {
    name: "Arsenic",
    appearance: "metallic gray",
    category: "metalloid",
    discovered_by: "Bronze Age",
    number: 33,
    period: 4,
    group: 15,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Arsenic",
    summary:
      "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in conjunction with sulfur and metals, and also as a pure elemental crystal. Arsenic is a metalloid.",
    symbol: "As",
    position: { row: 4, col: 15 },
    block: "p",
  },
  {
    name: "Selenium",
    appearance: "black, red, and gray (not pictured) allotropes",
    category: "polyatomic nonmetal",
    discovered_by: "Jöns Jakob Berzelius",
    number: 34,
    period: 4,
    group: 16,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Selenium",
    summary:
      "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium, and also has similarities to arsenic. It rarely occurs in its elemental state or as pure ore compounds in the Earth's crust.",
    symbol: "Se",
    position: { row: 4, col: 16 },
    block: "p",
  },
  {
    name: "Bromine",
    appearance: "reddish-brown",
    category: "diatomic nonmetal",
    discovered_by: "Antoine Jérôme Balard",
    number: 35,
    period: 4,
    group: 17,
    phase: "Liquid",
    source: "https://en.wikipedia.org/wiki/Bromine",
    summary:
      'Bromine (from Ancient Greek:βρῶμος, brómos, meaning "stench") is a chemical element with symbol Br, and atomic number 35. It is a halogen. It is a volatile red-brown liquid at room temperature that evaporates readily to form a similarly coloured gas.',
    symbol: "Br",
    position: { row: 4, col: 17 },
    block: "p",
  },
  {
    name: "Krypton",
    appearance:
      "colorless gas, exhibiting a whitish glow in a high electric field",
    category: "noble gas",
    discovered_by: "William Ramsay",
    number: 36,
    period: 4,
    group: 18,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Krypton",
    summary:
      'Krypton (from Greek:κρυπτός kryptos "the hidden one") is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere and is often used with other rare gases in fluorescent lamps.',
    symbol: "Kr",
    position: { row: 4, col: 18 },
    block: "p",
  },
  {
    name: "Rubidium",
    appearance: "grey white",
    category: "alkali metal",
    discovered_by: "Robert Bunsen",
    number: 37,
    period: 5,
    group: 1,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Rubidium",
    summary:
      "Rubidium is a chemical element with symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group, with an atomic mass of 85.4678. Elemental rubidium is highly reactive, with properties similar to those of other alkali metals, such as very rapid oxidation in air.",
    symbol: "Rb",
    position: { row: 5, col: 1 },
    block: "s",
  },
  {
    name: "Strontium",
    appearance: "silvery white metallic; with a pale yellow tint",
    category: "alkaline earth metal",
    discovered_by: "William Cruickshank (chemist)",
    number: 38,
    period: 5,
    group: 2,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Strontium",
    summary:
      "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly reactive chemically. The metal forms a dark oxide layer when it is exposed to air.",
    symbol: "Sr",
    position: { row: 5, col: 2 },
    block: "s",
  },
  {
    name: "Yttrium",
    appearance: "silvery white",
    category: "transition metal",
    discovered_by: "Johan Gadolin",
    number: 39,
    period: 5,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Yttrium",
    summary:
      'Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a "rare earth element". Yttrium is almost always found in combination with lanthanide elements in rare earth minerals, and is never found in nature as a free element.',
    symbol: "Y",
    position: { row: 5, col: 3 },
    block: "d",
  },
  {
    name: "Zirconium",
    appearance: "silvery white",
    category: "transition metal",
    discovered_by: "Martin Heinrich Klaproth",
    number: 40,
    period: 5,
    group: 4,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Zirconium",
    summary:
      'Zirconium is a chemical element with symbol Zr and atomic number 40. The name of zirconium is taken from the name of the mineral zircon, the most important source of zirconium. The word zircon comes from the Persian word zargun زرگون, meaning "gold-colored".',
    symbol: "Zr",
    position: { row: 5, col: 4 },
    block: "d",
  },
  {
    name: "Niobium",
    appearance: "gray metallic, bluish when oxidized",
    category: "transition metal",
    discovered_by: "Charles Hatchett",
    number: 41,
    period: 5,
    group: 5,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Niobium",
    summary:
      "Niobium, formerly columbium, is a chemical element with symbol Nb (formerly Cb) and atomic number 41. It is a soft, grey, ductile transition metal, which is often found in the pyrochlore mineral, the main commercial source for niobium, and columbite. The name comes from Greek mythology:Niobe, daughter of Tantalus since it is so similar to tantalum.",
    symbol: "Nb",
    position: { row: 5, col: 5 },
    block: "d",
  },
  {
    name: "Molybdenum",
    appearance: "gray metallic",
    category: "transition metal",
    discovered_by: "Carl Wilhelm Scheele",
    number: 42,
    period: 5,
    group: 6,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Molybdenum",
    summary:
      "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek Μόλυβδος molybdos, meaning lead, since its ores were confused with lead ores. Molybdenum minerals have been known throughout history, but the element was discovered (in the sense of differentiating it as a new entity from the mineral salts of other metals) in 1778 by Carl Wilhelm Scheele.",
    symbol: "Mo",
    position: { row: 5, col: 6 },
    block: "d",
  },
  {
    name: "Technetium",
    appearance: "shiny gray metal",
    category: "transition metal",
    discovered_by: "Emilio Segrè",
    number: 43,
    period: 5,
    group: 7,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Technetium",
    summary:
      "Technetium is a chemical element with symbol Tc and atomic number 43. It is the element with the lowest atomic number in the periodic table that has no stable isotopes:every form of it is radioactive. Nearly all technetium is produced synthetically, and only minute amounts are found in nature.",
    symbol: "Tc",
    position: { row: 5, col: 7 },
    block: "d",
  },
  {
    name: "Ruthenium",
    appearance: "silvery white metallic",
    category: "transition metal",
    discovered_by: "Karl Ernst Claus",
    number: 44,
    period: 5,
    group: 8,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Ruthenium",
    summary:
      "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table. Like the other metals of the platinum group, ruthenium is inert to most other chemicals.",
    symbol: "Ru",
    position: { row: 5, col: 8 },
    block: "d",
  },
  {
    name: "Rhodium",
    appearance: "silvery white metallic",
    category: "transition metal",
    discovered_by: "William Hyde Wollaston",
    number: 45,
    period: 5,
    group: 9,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Rhodium",
    summary:
      "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, corrosion-resistant transition metal. It is a noble metal and a member of the platinum group.",
    symbol: "Rh",
    position: { row: 5, col: 9 },
    block: "d",
  },
  {
    name: "Palladium",
    appearance: "silvery white",
    category: "transition metal",
    discovered_by: "William Hyde Wollaston",
    number: 46,
    period: 5,
    group: 10,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Palladium",
    summary:
      "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston. He named it after the asteroid Pallas, which was itself named after the epithet of the Greek goddess Athena, acquired by her when she slew Pallas.",
    symbol: "Pd",
    position: { row: 5, col: 10 },
    block: "d",
  },
  {
    name: "Silver",
    appearance: "lustrous white metal",
    category: "transition metal",
    discovered_by: "before 5000 BC",
    number: 47,
    period: 5,
    group: 11,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Silver",
    summary:
      'Silver is a chemical element with symbol Ag (from Latin argentum, derived from the Proto-Indo-European h₂erǵ: "shiny" or "white") and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.',
    symbol: "Ag",
    position: { row: 5, col: 11 },
    block: "d",
  },
  {
    name: "Cadmium",
    appearance: "silvery bluish-gray metallic",
    category: "transition metal",
    discovered_by: "Karl Samuel Leberecht Hermann",
    number: 48,
    period: 5,
    group: 12,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Cadmium",
    summary:
      "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury. Like zinc, it demonstrates oxidation state +2 in most of its compounds, and like mercury, it has a lower melting point than the transition metals in groups 3 through 11.",
    symbol: "Cd",
    position: { row: 5, col: 12 },
    block: "d",
  },
  {
    name: "Indium",
    appearance: "silvery lustrous gray",
    category: "post-transition metal",
    discovered_by: "Ferdinand Reich",
    number: 49,
    period: 5,
    group: 13,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Indium",
    summary:
      "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metal that makes up 0.21 parts per million of the Earth's crust. Very soft and malleable, indium has a melting point higher than sodium and gallium, but lower than lithium and tin.",
    symbol: "In",
    position: { row: 5, col: 13 },
    block: "p",
  },
  {
    name: "Tin",
    appearance: "silvery-white (beta, β) or gray (alpha, α)",
    category: "post-transition metal",
    discovered_by: "before 3500 BC",
    number: 50,
    period: 5,
    group: 14,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Tin",
    summary:
      "Tin is a chemical element with symbol Sn (from Latin stannum) and atomic number 50. It is a post-transition metal in group 14 of the periodic table. It is obtained chiefly from the mineral cassiterite, which contains tin dioxide.",
    symbol: "Sn",
    position: { row: 5, col: 14 },
    block: "p",
  },
  {
    name: "Antimony",
    appearance: "silvery lustrous gray",
    category: "metalloid",
    discovered_by: "before 3000 BC",
    number: 51,
    period: 5,
    group: 15,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Antimony",
    summary:
      "Antimony is a chemical element with symbol Sb (from Latin stibium) and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3). Antimony compounds have been known since ancient times and were powdered for use as medicine and cosmetics, often known by the Arabic name kohl.",
    symbol: "Sb",
    position: { row: 5, col: 15 },
    block: "p",
  },
  {
    name: "Tellurium",
    appearance: "silvery lustrous gray",
    category: "metalloid",
    discovered_by: "Franz-Joseph Müller von Reichenstein",
    number: 52,
    period: 5,
    group: 16,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Tellurium",
    summary:
      "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid. Tellurium is chemically related to selenium and sulfur. It is occasionally found in native form as elemental crystals.",
    symbol: "Te",
    position: { row: 5, col: 16 },
    block: "p",
  },
  {
    name: "Iodine",
    appearance: "lustrous metallic gray, violet as a gas",
    category: "diatomic nonmetal",
    discovered_by: "Bernard Courtois",
    number: 53,
    period: 5,
    group: 17,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Iodine",
    summary:
      "Iodine is a chemical element with symbol I and atomic number 53. The heaviest of the stable halogens, it exists as a lustrous, purple-black metallic solid at standard conditions that sublimes readily to form a violet gas. Iodine was discovered by the French chemist Bernard Courtois in 1811.",
    symbol: "I",
    position: { row: 5, col: 17 },
    block: "p",
  },
  {
    name: "Xenon",
    appearance:
      "colorless gas, exhibiting a blue glow when placed in a high-voltage electric field",
    category: "noble gas",
    discovered_by: "William Ramsay",
    number: 54,
    period: 5,
    group: 18,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Xenon",
    summary:
      "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts. Although generally unreactive, xenon can undergo a few chemical reactions such as the formation of xenon hexafluoroplatinate, the first noble gas compound to be synthesized.",
    symbol: "Xe",
    position: { row: 5, col: 18 },
    block: "p",
  },
  {
    name: "Caesium",
    appearance: "silvery gold",
    category: "alkali metal",
    discovered_by: "Robert Bunsen",
    number: 55,
    period: 6,
    group: 1,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Caesium",
    summary:
      "Caesium or cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-golden alkali metal with a melting point of 28.5 °C (83.3 °F), which makes it one of only five elemental metals that are liquid at or near room temperature.",
    symbol: "Cs",
    position: { row: 6, col: 1 },
    block: "s",
  },
  {
    name: "Barium",
    appearance: "silvery gray; with a pale yellow tint",
    category: "alkaline earth metal",
    discovered_by: "Carl Wilhelm Scheele",
    number: 56,
    period: 6,
    group: 2,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Barium",
    summary:
      "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in group 2 and is a soft, silvery alkaline earth metal. Because of its high chemical reactivity, barium is never found in nature as a free element.",
    symbol: "Ba",
    position: { row: 6, col: 2 },
    block: "s",
  },
  {
    name: "Lanthanum",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Carl Gustaf Mosander",
    number: 57,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Lanthanum",
    summary:
      "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, ductile, silvery-white metal that tarnishes slowly when exposed to air and is soft enough to be cut with a knife. It is the eponym of the lanthanide series, a group of 15 similar elements between lanthanum and lutetium in the periodic table.",
    symbol: "La",
    position: { row: 8, col: 3 },
    block: "f",
  },
  {
    name: "Cerium",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Martin Heinrich Klaproth",
    number: 58,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Cerium",
    summary:
      "Cerium is a chemical element with symbol Ce and atomic number 58. Cerium is a soft, ductile and silvery-white metal that tarnishes when exposed to air, and it is soft enough to be cut with a knife. Cerium is the second element in the lanthanide series, and while it often shows the +3 oxidation state characteristic of the series, it also has a stable +4 state that does not oxidize water.",
    symbol: "Ce",
    position: { row: 8, col: 4 },
    block: "f",
  },
  {
    name: "Praseodymium",
    appearance: "grayish white",
    category: "lanthanide",
    discovered_by: "Carl Auer von Welsbach",
    number: 59,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Praseodymium",
    summary:
      "Praseodymium is a chemical element with symbol Pr and atomic number 59. It is the third member of the lanthanide series and is traditionally considered to be one of the rare-earth metals. Praseodymium is a soft, silvery, malleable and ductile metal, valued for its magnetic, electrical, chemical, and optical properties.",
    symbol: "Pr",
    position: { row: 8, col: 5 },
    block: "f",
  },
  {
    name: "Neodymium",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Carl Auer von Welsbach",
    number: 60,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Neodymium",
    summary:
      "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a rare earth metal and is a member of the lanthanide series. Neodymium was discovered in 1885 by the Austrian chemist Carl Auer von Welsbach. It is present in significant quantities in the ore minerals monazite and bastnäsite.",
    symbol: "Nd",
    position: { row: 8, col: 6 },
    block: "f",
  },
  {
    name: "Promethium",
    appearance: "metallic",
    category: "lanthanide",
    discovered_by: "Jacob A. Marinsky",
    number: 61,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Promethium",
    summary:
      "Promethium is a chemical element with symbol Pm and atomic number 61. All of its isotopes are radioactive; it is one of only two such elements that are followed in the periodic table by elements with stable forms, a distinction shared with technetium. Chemically, promethium is a lanthanide, which forms salts when combined with other elements.",
    symbol: "Pm",
    position: { row: 8, col: 7 },
    block: "f",
  },
  {
    name: "Samarium",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Lecoq de Boisbaudran",
    number: 62,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Samarium",
    summary:
      "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that readily oxidizes in air. Being a typical member of the lanthanide series, samarium usually assumes the oxidation state +3.",
    symbol: "Sm",
    position: { row: 8, col: 8 },
    block: "f",
  },
  {
    name: "Europium",
    appearance:
      "silvery white, with a pale yellow tint; but rarely seen without oxide discoloration",
    category: "lanthanide",
    discovered_by: "Eugène-Anatole Demarçay",
    number: 63,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Europium",
    summary:
      "Europium is a chemical element with symbol Eu and atomic number 63. It was isolated in 1901 and is named after the continent of Europe. It is a moderately hard, silvery metal which readily oxidizes in air and water.",
    symbol: "Eu",
    position: { row: 8, col: 9 },
    block: "f",
  },
  {
    name: "Gadolinium",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Jean Charles Galissard de Marignac",
    number: 64,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Gadolinium",
    summary:
      "Gadolinium is a chemical element with symbol Gd and atomic number 64. Gadolinium is a silvery-white, malleable, and ductile rare earth metal. It is found in nature only in oxidized form, and when separated, it usually has impurities of the other rare earths.",
    symbol: "Gd",
    position: { row: 8, col: 10 },
    block: "f",
  },
  {
    name: "Terbium",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Carl Gustaf Mosander",
    number: 65,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Terbium",
    summary:
      "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife. The ninth member of the lanthanide series, terbium is a fairly electropositive metal that reacts with water, evolving hydrogen gas.",
    symbol: "Tb",
    position: { row: 8, col: 11 },
    block: "f",
  },
  {
    name: "Dysprosium",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Lecoq de Boisbaudran",
    number: 66,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Dysprosium",
    summary:
      "Dysprosium is a chemical element with symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster. Dysprosium is never found in nature as a free element, though it is found in various minerals, such as xenotime.",
    symbol: "Dy",
    position: { row: 8, col: 12 },
    block: "f",
  },
  {
    name: "Holmium",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Marc Delafontaine",
    number: 67,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Holmium",
    summary:
      "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare-earth element. Holmium was discovered by Swedish chemist Per Theodor Cleve.",
    symbol: "Ho",
    position: { row: 8, col: 13 },
    block: "f",
  },
  {
    name: "Erbium",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Carl Gustaf Mosander",
    number: 68,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Erbium",
    summary:
      "Erbium is a chemical element with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements. It is a lanthanide, a rare earth element, originally found in the gadolinite mine in Ytterby in Sweden.",
    symbol: "Er",
    position: { row: 8, col: 14 },
    block: "f",
  },
  {
    name: "Thulium",
    appearance: "silvery gray",
    category: "lanthanide",
    discovered_by: "Per Teodor Cleve",
    number: 69,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Thulium",
    summary:
      "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series. Like the other lanthanides, the most common oxidation state is +3, seen in its oxide, halides and other compounds.",
    symbol: "Tm",
    position: { row: 8, col: 15 },
    block: "f",
  },
  {
    name: "Ytterbium",
    appearance: "silvery white; with a pale yellow tint",
    category: "lanthanide",
    discovered_by: "Jean Charles Galissard de Marignac",
    number: 70,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Ytterbium",
    summary:
      "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state. However, like the other lanthanides, its most common oxidation state is +3.",
    symbol: "Yb",
    position: { row: 8, col: 16 },
    block: "f",
  },
  {
    name: "Lutetium",
    appearance: "silvery white",
    category: "lanthanide",
    discovered_by: "Georges Urbain",
    number: 71,
    period: 6,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Lutetium",
    summary:
      "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry air, but not in moist air. Lutetium is the last element in the lanthanide series, and it is traditionally counted among the rare earths.",
    symbol: "Lu",
    position: { row: 8, col: 17 },
    block: "f",
  },
  {
    name: "Hafnium",
    appearance: "steel gray",
    category: "transition metal",
    discovered_by: "Dirk Coster",
    number: 72,
    period: 6,
    group: 4,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Hafnium",
    summary:
      "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals. Its existence was predicted by Dmitri Mendeleev in 1869.",
    symbol: "Hf",
    position: { row: 6, col: 4 },
    block: "d",
  },
  {
    name: "Tantalum",
    appearance: "gray blue",
    category: "transition metal",
    discovered_by: "Anders Gustaf Ekeberg",
    number: 73,
    period: 6,
    group: 5,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Tantalum",
    summary:
      "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, its name comes from Tantalus, a villain from Greek mythology. Tantalum is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant.",
    symbol: "Ta",
    position: { row: 6, col: 5 },
    block: "d",
  },
  {
    name: "Tungsten",
    appearance: "grayish white, lustrous",
    category: "transition metal",
    discovered_by: "Carl Wilhelm Scheele",
    number: 74,
    period: 6,
    group: 6,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Tungsten",
    summary:
      'Tungsten, or wolfram, is a chemical element with symbol W and atomic number 74. The name tungsten comes from the former Swedish name for the tungstate mineral scheelite, tungsten which means "heavy stone". Tungsten is a rare metal found naturally on Earth almost exclusively in chemical compounds.',
    symbol: "W",
    position: { row: 6, col: 6 },
    block: "d",
  },
  {
    name: "Rhenium",
    appearance: "silvery-grayish",
    category: "transition metal",
    discovered_by: "Masataka Ogawa",
    number: 75,
    period: 6,
    group: 7,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Rhenium",
    summary:
      "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-gray, heavy, third-row transition metal in group 7 of the periodic table. With an estimated average concentration of 1 part per billion (ppb), rhenium is one of the rarest elements in the Earth's crust.",
    symbol: "Re",
    position: { row: 6, col: 7 },
    block: "d",
  },
  {
    name: "Osmium",
    appearance: "silvery, blue cast",
    category: "transition metal",
    discovered_by: "Smithson Tennant",
    number: 76,
    period: 6,
    group: 8,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Osmium",
    summary:
      "Osmium (from Greek osme, 'smell') is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores. Osmium is the densest naturally occurring element.",
    symbol: "Os",
    position: { row: 6, col: 8 },
    block: "d",
  },
  {
    name: "Iridium",
    appearance: "silvery white",
    category: "transition metal",
    discovered_by: "Smithson Tennant",
    number: 77,
    period: 6,
    group: 9,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Iridium",
    summary:
      "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is generally credited with being the second densest element (after osmium). It is also the most corrosion-resistant metal, even at temperatures as high as 2000 °C.",
    symbol: "Ir",
    position: { row: 6, col: 9 },
    block: "d",
  },
  {
    name: "Platinum",
    appearance: "silvery white",
    category: "transition metal",
    discovered_by: "Antonio de Ulloa",
    number: 78,
    period: 6,
    group: 10,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Platinum",
    summary:
      'Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal. Its name is derived from the Spanish term platino, meaning "little silver".',
    symbol: "Pt",
    position: { row: 6, col: 10 },
    block: "d",
  },
  {
    name: "Gold",
    appearance: "metallic yellow",
    category: "transition metal",
    discovered_by: "before 6000 BC",
    number: 79,
    period: 6,
    group: 11,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Gold",
    summary:
      "Gold is a chemical element with symbol Au (from Latin aurum) and atomic number 79. This makes it one of the higher atomic number elements that occur naturally. It is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.",
    symbol: "Au",
    position: { row: 6, col: 11 },
    block: "d",
  },
  {
    name: "Mercury",
    appearance: "silvery",
    category: "transition metal",
    discovered_by: "before 2000 BC",
    number: 80,
    period: 6,
    group: 12,
    phase: "Liquid",
    source: "https://en.wikipedia.org/wiki/Mercury (element)",
    summary:
      "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum. A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure.",
    symbol: "Hg",
    position: { row: 6, col: 12 },
    block: "d",
  },
  {
    name: "Thallium",
    appearance: "silvery white",
    category: "post-transition metal",
    discovered_by: "William Crookes",
    number: 81,
    period: 6,
    group: 13,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Thallium",
    summary:
      "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature. When isolated, thallium resembles tin, but discolors when exposed to air.",
    symbol: "Tl",
    position: { row: 6, col: 13 },
    block: "p",
  },
  {
    name: "Lead",
    appearance: "metallic gray",
    category: "post-transition metal",
    discovered_by: "before 7000 BC",
    number: 82,
    period: 6,
    group: 14,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Lead",
    summary:
      "Lead is a chemical element with symbol Pb (from Latin plumbum) and atomic number 82. It is a heavy metal that is denser than most common materials. Lead is soft and malleable, and also has a relatively low melting point.",
    symbol: "Pb",
    position: { row: 6, col: 14 },
    block: "p",
  },
  {
    name: "Bismuth",
    appearance: "lustrous silver",
    category: "post-transition metal",
    discovered_by: "Claude François Geoffroy",
    number: 83,
    period: 6,
    group: 15,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Bismuth",
    summary:
      "Bismuth is a chemical element with symbol Bi and atomic number 83. It is a pentavalent post-transition metal and one of the pnictogens with chemical properties resembling its lighter group 15 siblings arsenic and antimony.",
    symbol: "Bi",
    position: { row: 6, col: 15 },
    block: "p",
  },
  {
    name: "Polonium",
    appearance: "silvery",
    category: "post-transition metal",
    discovered_by: "Pierre Curie",
    number: 84,
    period: 6,
    group: 16,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Polonium",
    summary:
      "Polonium is a chemical element with symbol Po and atomic number 84. A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to selenium and tellurium, though its metallic character resembles that of its horizontal neighbors in the periodic table: thallium, lead, and bismuth.",
    symbol: "Po",
    position: { row: 6, col: 16 },
    block: "p",
  },
  {
    name: "Astatine",
    appearance: "unknown, probably metallic",
    category: "metalloid",
    discovered_by: "Dale R. Corson",
    number: 85,
    period: 6,
    group: 17,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Astatine",
    summary:
      "Astatine is a chemical element with symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth's crust, occurring only as the decay product of various heavier elements. All of astatine's isotopes are short-lived; the most stable is astatine-210, with a half-life of 8.1 hours.",
    symbol: "At",
    position: { row: 6, col: 17 },
    block: "p",
  },
  {
    name: "Radon",
    appearance: "colorless gas",
    category: "noble gas",
    discovered_by: "Friedrich Ernst Dorn",
    number: 86,
    period: 6,
    group: 18,
    phase: "Gas",
    source: "https://en.wikipedia.org/wiki/Radon",
    summary:
      "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas. It occurs naturally in minute quantities as an intermediate step in the normal radioactive decay chains through which thorium and uranium slowly decay into lead.",
    symbol: "Rn",
    position: { row: 6, col: 18 },
    block: "p",
  },
  {
    name: "Francium",
    appearance: "unknown, but probably metallic",
    category: "alkali metal",
    discovered_by: "Marguerite Perey",
    number: 87,
    period: 7,
    group: 1,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Francium",
    summary:
      "Francium is a chemical element with symbol Fr and atomic number 87. It is extremely radioactive; its most stable isotope, francium-223 (originally called actinium K after the natural decay chain it appears in), has a half-life of only 22 minutes. It is the second-least electronegative element, behind only caesium.",
    symbol: "Fr",
    position: { row: 7, col: 1 },
    block: "s",
  },
  {
    name: "Radium",
    appearance: "silvery white metallic",
    category: "alkaline earth metal",
    discovered_by: "Pierre Curie",
    number: 88,
    period: 7,
    group: 2,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Radium",
    summary:
      "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals. Pure radium is silvery-white, but it readily combines with nitrogen (rather than oxygen) on exposure to air, forming a black surface layer of radium nitride.",
    symbol: "Ra",
    position: { row: 7, col: 2 },
    block: "s",
  },
  {
    name: "Actinium",
    appearance:
      "silvery-white, glowing with an eerie blue light; sometimes with a yellow cast because of radioactivity",
    category: "actinide",
    discovered_by: "Friedrich Oskar Giesel",
    number: 89,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Actinium",
    summary:
      "Actinium is a chemical element with symbol Ac and atomic number 89. It was discovered in 1899 by Friedrich Oskar Giesel, who gave it the name emanium; the element got its name by being incorrectly identified with a substance André-Louis Debierne found in 1899 and called actinium.",
    symbol: "Ac",
    position: { row: 9, col: 3 },
    block: "f",
  },
  {
    name: "Thorium",
    appearance: "silvery, often with black tarnish",
    category: "actinide",
    discovered_by: "Jöns Jakob Berzelius",
    number: 90,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Thorium",
    summary:
      "Thorium is a chemical element with symbol Th and atomic number 90. A radioactive actinide metal, thorium is one of only two significantly radioactive elements that still occur naturally in large quantities as a primordial element (the other being uranium).",
    symbol: "Th",
    position: { row: 9, col: 4 },
    block: "f",
  },
  {
    name: "Protactinium",
    appearance: "bright, silvery metallic luster",
    category: "actinide",
    discovered_by: "William Crookes",
    number: 91,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Protactinium",
    summary:
      "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray metal which readily reacts with oxygen, water vapor and inorganic acids. It forms various chemical compounds in which protactinium is usually present in the oxidation state +5, but it can also assume +4 and even +3 or +2 states.",
    symbol: "Pa",
    position: { row: 9, col: 5 },
    block: "f",
  },
  {
    name: "Uranium",
    appearance:
      "silvery gray metallic; corrodes to a spalling black oxide coat in air",
    category: "actinide",
    discovered_by: "Martin Heinrich Klaproth",
    number: 92,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Uranium",
    summary:
      "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-grey metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons. Uranium is weakly radioactive because all isotopes of uranium are unstable, with half-lives varying between 159,200 years and 4.5 billion years.",
    symbol: "U",
    position: { row: 9, col: 6 },
    block: "f",
  },
  {
    name: "Neptunium",
    appearance: "silvery metallic",
    category: "actinide",
    discovered_by: "Edwin McMillan",
    number: 93,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Neptunium",
    summary:
      "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element. Its position in the periodic table just after uranium, named after the planet Uranus, led to it being named after Neptune, the next planet beyond Uranus.",
    symbol: "Np",
    position: { row: 9, col: 7 },
    block: "f",
  },
  {
    name: "Plutonium",
    appearance: "silvery white, tarnishing to dark gray in air",
    category: "actinide",
    discovered_by: "Glenn T. Seaborg",
    number: 94,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Plutonium",
    summary:
      "Plutonium is a chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized. The element normally exhibits six allotropes and four oxidation states.",
    symbol: "Pu",
    position: { row: 9, col: 8 },
    block: "f",
  },
  {
    name: "Americium",
    appearance: "silvery white",
    category: "actinide",
    discovered_by: "Glenn T. Seaborg",
    number: 95,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Americium",
    summary:
      "Americium is a chemical element with symbol Am and atomic number 95. It is a radioactive transuranic member of the actinide series, in the periodic table located under the lanthanide element europium, and thus by analogy was named after the Americas.",
    symbol: "Am",
    position: { row: 9, col: 9 },
    block: "f",
  },
  {
    name: "Curium",
    appearance: "silvery metallic, glows purple in the dark",
    category: "actinide",
    discovered_by: "Glenn T. Seaborg",
    number: 96,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Curium",
    summary:
      "Curium is a chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie – both were known for their research on radioactivity. Curium was first intentionally produced and identified in July 1944 by the group of Glenn T. Seaborg at the University of California, Berkeley.",
    symbol: "Cm",
    position: { row: 9, col: 10 },
    block: "f",
  },
  {
    name: "Berkelium",
    appearance: "silvery",
    category: "actinide",
    discovered_by: "Lawrence Berkeley National Laboratory",
    number: 97,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Berkelium",
    summary:
      "Berkelium is a chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series. It is named after the city of Berkeley, California, the location of the University of California Radiation Laboratory where it was discovered in December 1949.",
    symbol: "Bk",
    position: { row: 9, col: 11 },
    block: "f",
  },
  {
    name: "Californium",
    appearance: "silvery",
    category: "actinide",
    discovered_by: "Lawrence Berkeley National Laboratory",
    number: 98,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Californium",
    summary:
      "Californium is a chemical element with symbol Cf and atomic number 98. The element was first synthesized in 1950 at the Lawrence Berkeley National Laboratory (then the University of California Radiation Laboratory), by bombarding curium with alpha particles (helium-4 ions). It is an actinide element, the sixth transuranium element to be synthesized.",
    symbol: "Cf",
    position: { row: 9, col: 12 },
    block: "f",
  },
  {
    name: "Einsteinium",
    appearance: "silver-colored",
    category: "actinide",
    discovered_by: "Lawrence Berkeley National Laboratory",
    number: 99,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Einsteinium",
    summary:
      "Einsteinium is a chemical element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide. Einsteinium was discovered as a component of the debris of the first hydrogen bomb explosion in 1952, and named after Albert Einstein.",
    symbol: "Es",
    position: { row: 9, col: 13 },
    block: "f",
  },
  {
    name: "Fermium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "actinide",
    discovered_by: "Lawrence Berkeley National Laboratory",
    number: 100,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Fermium",
    summary:
      "Fermium is a chemical element with symbol Fm and atomic number 100. It is an actinide and the heaviest element that can be formed by neutron bombardment of lighter elements, and hence the last element that can be prepared in macroscopic quantities, although pure fermium metal has not yet been prepared.",
    symbol: "Fm",
    position: { row: 9, col: 14 },
    block: "f",
  },
  {
    name: "Mendelevium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "actinide",
    discovered_by: "Lawrence Berkeley National Laboratory",
    number: 101,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Mendelevium",
    summary:
      "Mendelevium is a chemical element with symbol Md and atomic number 101. A metallic radioactive transuranic element in the actinide series, it is the first element by atomic number that currently cannot be produced in macroscopic quantities through neutron bombardment of lighter elements.",
    symbol: "Md",
    position: { row: 9, col: 15 },
    block: "f",
  },
  {
    name: "Nobelium",
    appearance:
      "unknown, but probably metallic and silvery or gray in appearance",
    category: "actinide",
    discovered_by: "Joint Institute for Nuclear Research",
    number: 102,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Nobelium",
    summary:
      "Nobelium is a chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science. A radioactive metal, it is the tenth transuranic element and is the penultimate member of the actinide series.",
    symbol: "No",
    position: { row: 9, col: 16 },
    block: "f",
  },
  {
    name: "Lawrencium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "actinide",
    discovered_by: "Lawrence Berkeley National Laboratory",
    number: 103,
    period: 7,
    group: 3,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Lawrencium",
    summary:
      "Lawrencium is a chemical element with symbol Lr and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements. A radioactive metal, lawrencium is the eleventh transuranic element and is also the final member of the actinide series.",
    symbol: "Lr",
    position: { row: 9, col: 17 },
    block: "f",
  },

  // Elements 104-118 (continuing main table after actinides)
  {
    name: "Rutherfordium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "transition metal",
    discovered_by: "Joint Institute for Nuclear Research",
    number: 104,
    period: 7,
    group: 4,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Rutherfordium",
    summary:
      "Rutherfordium is a chemical element with symbol Rf and atomic number 104, named after physicist Ernest Rutherford. As a synthetic element, it is not found in nature and can only be created in a laboratory. It is radioactive; the most stable known isotope, 267Rf, has a half-life of approximately 1.3 hours.",
    symbol: "Rf",
    position: { row: 7, col: 4 },
    block: "d",
  },
  {
    name: "Dubnium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "transition metal",
    discovered_by: "Joint Institute for Nuclear Research",
    number: 105,
    period: 7,
    group: 5,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Dubnium",
    summary:
      "Dubnium is a chemical element with symbol Db and atomic number 105. It is named after the town of Dubna in Russia (north of Moscow), where it was first produced. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, dubnium-268, has a half-life of approximately 28 hours.",
    symbol: "Db",
    position: { row: 7, col: 5 },
    block: "d",
  },
  {
    name: "Seaborgium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "transition metal",
    discovered_by: "Lawrence Berkeley National Laboratory",
    number: 106,
    period: 7,
    group: 6,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Seaborgium",
    summary:
      "Seaborgium is a chemical element with symbol Sg and atomic number 106. It is named after the American nuclear chemist Glenn T. Seaborg. As a synthetic element, it can be created in a laboratory but is not found in nature. It is also radioactive; the most stable known isotope, 269Sg, has a half-life of approximately 14 minutes.",
    symbol: "Sg",
    position: { row: 7, col: 6 },
    block: "d",
  },
  {
    name: "Bohrium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "transition metal",
    discovered_by: "Gesellschaft für Schwerionenforschung",
    number: 107,
    period: 7,
    group: 7,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Bohrium",
    summary:
      "Bohrium is a chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr. As a synthetic element, it can be created in a laboratory but is not found in nature. All known isotopes of bohrium are highly radioactive; the most stable known isotope is 270Bh with a half-life of approximately 61 seconds.",
    symbol: "Bh",
    position: { row: 7, col: 7 },
    block: "d",
  },
  {
    name: "Hassium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "transition metal",
    discovered_by: "Gesellschaft für Schwerionenforschung",
    number: 108,
    period: 7,
    group: 8,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Hassium",
    summary:
      "Hassium is a chemical element with symbol Hs and atomic number 108. It is named after the German state of Hesse. As a synthetic element, it can be created in a laboratory but is not found in nature. All known isotopes of hassium are highly radioactive; the most stable known isotope is 277Hs with a half-life of approximately 11 minutes.",
    symbol: "Hs",
    position: { row: 7, col: 8 },
    block: "d",
  },
  {
    name: "Meitnerium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "transition metal",
    discovered_by: "Gesellschaft für Schwerionenforschung",
    number: 109,
    period: 7,
    group: 9,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Meitnerium",
    summary:
      "Meitnerium is a chemical element with symbol Mt and atomic number 109. It is named after Lise Meitner. As a synthetic element, it can be created in a laboratory but is not found in nature. All known isotopes of meitnerium are highly radioactive; the most stable known isotope is 278Mt with a half-life of approximately 8 seconds.",
    symbol: "Mt",
    position: { row: 7, col: 9 },
    block: "d",
  },
  {
    name: "Darmstadtium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "transition metal",
    discovered_by: "Gesellschaft für Schwerionenforschung",
    number: 110,
    period: 7,
    group: 10,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Darmstadtium",
    summary:
      "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is an extremely radioactive synthetic element. The most stable known isotope, darmstadtium-281, has a half-life of approximately 12.7 seconds. Darmstadtium was first created in 1994 by the GSI Helmholtz Centre for Heavy Ion Research near the city of Darmstadt, Germany, after which it was named.",
    symbol: "Ds",
    position: { row: 7, col: 10 },
    block: "d",
  },
  {
    name: "Roentgenium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "transition metal",
    discovered_by: "Gesellschaft für Schwerionenforschung",
    number: 111,
    period: 7,
    group: 11,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Roentgenium",
    summary:
      "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is an extremely radioactive synthetic element that can be created in a laboratory but is not found in nature. The most stable known isotope, roentgenium-282, has a half-life of 100 seconds, although the unconfirmed roentgenium-286 may have a longer half-life of about 10.7 minutes.",
    symbol: "Rg",
    position: { row: 7, col: 11 },
    block: "d",
  },
  {
    name: "Copernicium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "transition metal",
    discovered_by: "Gesellschaft für Schwerionenforschung",
    number: 112,
    period: 7,
    group: 12,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Copernicium",
    summary:
      "Copernicium is a chemical element with symbol Cn and atomic number 112. It is an extremely radioactive synthetic element that can be created in a laboratory but is not found in nature. The most stable known isotope, copernicium-285, has a half-life of approximately 28 seconds. Copernicium was first created in 1996 by the GSI Helmholtz Centre for Heavy Ion Research.",
    symbol: "Cn",
    position: { row: 7, col: 12 },
    block: "d",
  },
  {
    name: "Nihonium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "post-transition metal",
    discovered_by: "RIKEN",
    number: 113,
    period: 7,
    group: 13,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Nihonium",
    summary:
      "Nihonium is a chemical element with symbol Nh and atomic number 113. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and is extremely radioactive; its most stable known isotope, nihonium-286, has a half-life of about 20 seconds. The element is named after Japan (Nihon in Japanese).",
    symbol: "Nh",
    position: { row: 7, col: 13 },
    block: "p",
  },
  {
    name: "Flerovium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "post-transition metal",
    discovered_by: "Joint Institute for Nuclear Research",
    number: 114,
    period: 7,
    group: 14,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Flerovium",
    summary:
      "Flerovium is a chemical element with symbol Fl and atomic number 114. It is an extremely radioactive synthetic element. The element is named after the Flerov Laboratory of Nuclear Reactions of the Joint Institute for Nuclear Research in Dubna, Russia, where the element was discovered in 1998.",
    symbol: "Fl",
    position: { row: 7, col: 14 },
    block: "p",
  },
  {
    name: "Moscovium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "post-transition metal",
    discovered_by: "Joint Institute for Nuclear Research",
    number: 115,
    period: 7,
    group: 15,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Moscovium",
    summary:
      "Moscovium is a chemical element with symbol Mc and atomic number 115. It was first synthesized in 2003 by a joint team of Russian and American scientists at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia. The element is named after the Moscow Oblast.",
    symbol: "Mc",
    position: { row: 7, col: 15 },
    block: "p",
  },
  {
    name: "Livermorium",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "post-transition metal",
    discovered_by: "Joint Institute for Nuclear Research",
    number: 116,
    period: 7,
    group: 16,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Livermorium",
    summary:
      "Livermorium is a chemical element with symbol Lv and atomic number 116. It is an extremely radioactive synthetic element that has only been created in the laboratory and has not been observed in nature. The element is named after the Lawrence Livermore National Laboratory in the United States.",
    symbol: "Lv",
    position: { row: 7, col: 16 },
    block: "p",
  },
  {
    name: "Tennessine",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "metalloid",
    discovered_by: "Joint Institute for Nuclear Research",
    number: 117,
    period: 7,
    group: 17,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Tennessine",
    summary:
      "Tennessine is a chemical element with symbol Ts and atomic number 117. It is the second-heaviest known element and the penultimate element of the 7th period of the periodic table. The discovery of tennessine was officially announced in 2010 by scientists from the Joint Institute for Nuclear Research in Dubna, Russia, and the Oak Ridge National Laboratory in Tennessee, USA.",
    symbol: "Ts",
    position: { row: 7, col: 17 },
    block: "p",
  },
  {
    name: "Oganesson",
    appearance:
      "unknown, but probably metallic and silvery white or gray in appearance",
    category: "noble gas",
    discovered_by: "Joint Institute for Nuclear Research",
    number: 118,
    period: 7,
    group: 18,
    phase: "Solid",
    source: "https://en.wikipedia.org/wiki/Oganesson",
    summary:
      "Oganesson is a chemical element with symbol Og and atomic number 118. It was first synthesized in 2002 at the Joint Institute for Nuclear Research (JINR) in Dubna, near Moscow, Russia, by a joint team of Russian and American scientists. In December 2015, it was recognized as one of four new elements by the Joint Working Party of international scientific bodies IUPAC and IUPAP.",
    symbol: "Og",
    position: { row: 7, col: 18 },
    block: "p",
  },
];

const periodicTable = document.querySelector("#periodic-table");

elements.forEach((ele) => {
  const div = document.createElement("div");
  div.classList.add("element");
  div.style.gridRow = ele.position.row;
  div.style.gridColumn = ele.position.col;
  div.innerHTML = `
    <div class="number">${ele.number}</div>
    <div class="symbol">${ele.symbol}</div>
    <div class="name">${ele.name}</div>
  `;
  div.setAttribute("data-category", ele.category);

  periodicTable.append(div);

  // popup creation on element click
  div.addEventListener("click", () => {
    const popupContainer = document.createElement("div");
    popupContainer.classList.add("popup-container", "active-popup");

    const popup = document.createElement("div");
    popup.classList.add("popup", ele.category.replace(/\s+/g, "-"));
    popup.innerHTML = `
      <div class="popup-header">
        <button class="close-popup">&times;</button>
        <div class="popup-symbol">${ele.symbol}</div>
        <h3 class="popup-heading">${ele.name}</h3>
      </div>
      <div class="popup-content">
        <p><strong>Name:</strong> ${ele.name}</p>
        <p><strong>Number:</strong> ${ele.number}</p>
        <p><strong>Block:</strong> ${ele.block}</p>
        <p><strong>Appearance:</strong> ${ele.appearance}</p>
        <p><strong>Category:</strong> ${ele.category}</p>
        <p><strong>Discovered By:</strong> ${ele.discovered_by}</p>
        <p><strong>Phase:</strong> ${ele.phase}</p>
        <p><strong>Source:</strong> ${ele.source}</p>
      </div>
    `;

    popupContainer.appendChild(popup);
    document.body.appendChild(popupContainer);

    // close popup
    popupContainer.addEventListener("click", (e) => {
      if (
        e.target === popupContainer ||
        e.target.classList.contains("close-popup")
      ) {
        popupContainer.remove();
      }
    });
  });
});

// filter buttons
const alkaliButton = document.querySelector(".alkali-button");
const diatomicButton = document.querySelector(".diatomic-button");
const nobleButton = document.querySelector(".noble-button");
const metalloidButton = document.querySelector(".metalloid-button");
const postTransitionButton = document.querySelector(".post-transition-button");
const alkalineEarthButton = document.querySelector(".alkaline-earth-button");
const polyatomicButton = document.querySelector(".polyatomic-button");
const lanthanideButton = document.querySelector(".lanthanide");
const actinideButton = document.querySelector(".actinide");

const filterButtons = document.querySelector(".filter-buttons");

alkaliButton.addEventListener("click", () => {
  filterButtons.setAttribute("filter-category", "alkali metal");
});

diatomicButton.addEventListener("click", () => {
  filterButtons.setAttribute("filter-category", "diatomic nonmetal");
});
